name: Reliable Multicast Release

run-name: ${{github.actor}} Debian Release Reliable Multicast

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-debian-pkg:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: sudo apt install git ruby-rubygems squashfs-tools

      - name: Install fpm
        run: sudo gem install fpm

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Debian packages
        run: make debian
      - run: ls -R

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.deb"
          name: Reliable Multicast Debian Release ${{ github.ref }}
